/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pat0gen0
 */
public class AlarmDialog extends javax.swing.JDialog {

    ClockFrame parent;

    /**
     * Creates new form dAlarm
     */
    public AlarmDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        // I add this
        this.parent = (ClockFrame) parent;
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        clockLabel1 = new back.ClockLabel();
        spHour = new javax.swing.JSpinner();
        btSend = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spMin = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lAlarmMsg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clockLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        clockLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockLabel1.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jPanel2.add(clockLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 188, 350, 100));

        spHour.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        spHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        spHour.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(spHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 62, 52));

        btSend.setBackground(java.awt.Color.orange);
        btSend.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btSend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btSend.setText("SET ALARM");
        btSend.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btSend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSend.setOpaque(true);
        btSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSendMouseClicked(evt);
            }
        });
        jPanel2.add(btSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clockito.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 150));

        spMin.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        spMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        spMin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        spMin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(spMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 62, 52));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Min");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 40, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hour");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, -1));

        lAlarmMsg.setBackground(java.awt.Color.white);
        lAlarmMsg.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lAlarmMsg.setForeground(java.awt.Color.lightGray);
        lAlarmMsg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lAlarmMsg.setText("Add your alarm message");
        lAlarmMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAlarmMsgMouseClicked(evt);
            }
        });
        lAlarmMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lAlarmMsgActionPerformed(evt);
            }
        });
        jPanel2.add(lAlarmMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSendMouseClicked
        int hour = (int) spHour.getValue();
        int min = (int) spMin.getValue();
        String msg = lAlarmMsg.getText();

        parent.getAlarmDialogData(hour, min, msg);

        try {
            parent.formatLAlarm();
            parent.OnAlarm();
        } catch (ParseException ex) {}
        dispose();
    }//GEN-LAST:event_btSendMouseClicked

    private void lAlarmMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lAlarmMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lAlarmMsgActionPerformed

    private void lAlarmMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAlarmMsgMouseClicked
        lAlarmMsg.setText("");
    }//GEN-LAST:event_lAlarmMsgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlarmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlarmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlarmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlarmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AlarmDialog dialog = new AlarmDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btSend;
    private back.ClockLabel clockLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lAlarmMsg;
    private javax.swing.JSpinner spHour;
    private javax.swing.JSpinner spMin;
    // End of variables declaration//GEN-END:variables
}
